### ISSUE TITLE
Fork of reliese-laravel

### ISSUE THREAD

**Issue by nasatome** [pursehouse/modeler-laravel-eloquent#1]
you're taking over an official fork? do you intend to keep it with time?

**Comment by gareth-ib** [comment]
hey @nasatome  yes I plan on keeping it going. Any help on features would be great. I'm hoping for aggressive enhancements of the system. Mostly for me because of Postgres having so many more features beyond what normal laravel/mysql people are aware of

**Comment by nasatome** [comment]
have you thought about looking for other maintainers?...to make a group, I noticed that it took a long time for you to answer this message

**Comment by gareth-ib** [comment]
yes I'd love help with it! I just added field-type based custom casting class ability. There are a lot of fixes I can see that the code could use... reorganizing... etc

**Comment by nasatome** [comment]
I think that's great. I'm going to "advertise" for you. hahaha

**Comment by gareth-ib** [comment]
haha thanks, any feature ideas you implement/think of, please pop in some new issues or PR's, so we don't lose track
