### ISSUE TITLE
Not work on Laravel 6.5.1

### ISSUE THREAD

**Issue by ivanceb26** [pursehouse/modeler-laravel-eloquent#3]
I use normally Reliese for model creation, but it isnt option for laravel 6.*.
I installed this package but dont work for me, my version is 6.5.1. 
When I use "php artisan pursehouse:modeler --table=mytable" show this:

>    Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1102 Incorrect database name '' (SQL: SHOW FULL TABLES FROM `` WHERE Table_type="BASE TABLE")

The connection with database is successful and tested with existent models.
I have already followed the steps one to one, from git instructions, 
but I haven't made it work.
You can test this version? thanks.

**Comment by gareth-ib** [comment]
I'm upgrading to 6.5 now to try it out

**Comment by gareth-ib** [comment]
```bash
php artisan pursehouse:modeler --connection=pgsql --schema=site --table=article
Making models for table : article
Check out your models for article
```
runs fine for me. Would be more helpful if you included the stack. But you might wanna check your permissions

**Comment by pursehouse** [comment]
feel free to re-open if you can show more info on this issue
